package voidblue.preference.demo.Models;

import lombok.Data;

@Data
public class TrainingOutput {
    private int 한라산;
    private int 오름;
    private int 성산일출봉;
    private int 섬;
    private int 올레길;
    private int 폭포;
    private int 동굴;
    private int 해수욕장;
    private int 비자림;
    private int 한라수목원;
    private int 서귀포자연휴양림;
    private int 절물자연휴양림;
    private int 용두암;
    private int 주상절리대;
    private int 한림공원;
    private int 국립제주박물관;
    private int 도립미술관;
    private int 민속자연사박물관;
    private int 제주돌문화공원;
    private int 제주세계자연유산센터;
    private int 이중섭박물관;
    private int 서복전시관;
    private int 제주43평화공원;
    private int 동문시장;
    private int 중앙로지하상가;
    private int 바오젠거리;
    private int 제주오일장;
    private int 서귀포매일올레시장;
    private int 신라면세점;
    private int 롯데면세점;
    private int 제주관광공사면세점;
    private int 공항JDC면세점;
    private int 제주목관아;
    private int 항몽유적지;
    private int 성읍민속마을;
    private int 삼양동선사유적;
    private int 제주추사관;
    private int 관덕정;
    private int 이중섭거주지;
    private int 하멜기념비;
    private int 미로공원;
    private int 에코랜드;
    private int 제주경마공원;
    private int 불교사찰;
    private int 아쿠아플라넷;
    private int 테디베어박물관;
    private int 소인국테마파크;
    private int 잠수함관광;
    private int 신비의도로;
    private int 생각하는정원;
    private int 드라마촬영지;
    private int 제주별빛누리공원;
    private int 유람선;
    private int 제주바다체험장;
    private int 골프장;
    private int 카지노;
}
